spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_test
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  sql:
    init:
      mode: never

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 1

cookie:
  secure: false

jwt:
  secret:
    key: ${JWT_SECRET:tttttttteeeeeeeesssssssstttttttt}

admin:
  key: ${ADMIN_KEY:test}